const {
  e,
  en,
  push_export
} = require('./api');

e.SDL_BLENDMODE_NONE = en(0x00000000);
e.SDL_BLENDMODE_BLEND = en(0x00000001);
e.SDL_BLENDMODE_ADD = en(0x00000002);
e.SDL_BLENDMODE_MOD = en(0x00000004);
e.SDL_BLENDMODE_MUL = en(0x00000008);
e.SDL_BLENDMODE_INVALID = en(0x7FFFFFFF);

e.SDL_BLENDOPERATION_ADD = en(0x1);
e.SDL_BLENDOPERATION_SUBTRACT = en(0x2);
e.SDL_BLENDOPERATION_REV_SUBTRACT = en(0x3);
e.SDL_BLENDOPERATION_MINIMUM = en(0x4);
e.SDL_BLENDOPERATION_MAXIMUM = en(0x5);

e.SDL_BLENDFACTOR_ZERO = en(0x1);
e.SDL_BLENDFACTOR_ONE = en(0x2);
e.SDL_BLENDFACTOR_SRC_COLOR = en(0x3);
e.SDL_BLENDFACTOR_ONE_MINUS_SRC_COLOR = en(0x4);
e.SDL_BLENDFACTOR_SRC_ALPHA = en(0x5);
e.SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA = en(0x6);
e.SDL_BLENDFACTOR_DST_COLOR = en(0x7);
e.SDL_BLENDFACTOR_ONE_MINUS_DST_COLOR = en(0x8);
e.SDL_BLENDFACTOR_DST_ALPHA = en(0x9);
e.SDL_BLENDFACTOR_ONE_MINUS_DST_ALPHA = en(0xA);

push_export({
  'SDL_ComposeCustomBlendMode': ['int', ['int', 'int', 'int', 'int', 'int', 'int']]
});
