const {
  e,
  l,
  ffi,
  ref,
  Struct,
  Union,
  from_hex,
  en,
  push_export,
  push_functions
} = require('./api');

e.SDL_CONTROLLER_TYPE_UNKNOWN = en(0);
e.SDL_CONTROLLER_TYPE_XBOX360 = en();
e.SDL_CONTROLLER_TYPE_XBOXONE = en();
e.SDL_CONTROLLER_TYPE_PS3 = en();
e.SDL_CONTROLLER_TYPE_PS4 = en();
e.SDL_CONTROLLER_TYPE_NINTENDO_SWITCH_PRO = en();
e.SDL_CONTROLLER_TYPE_VIRTUAL = en();
e.SDL_CONTROLLER_TYPE_PS5 = en();
e.SDL_CONTROLLER_TYPE_AMAZON_LUNA = en();
e.SDL_CONTROLLER_TYPE_GOOGLE_STADIA = en();

e.SDL_CONTROLLER_BINDTYPE_NONE = en(0);
e.SDL_CONTROLLER_BINDTYPE_BUTTON = en();
e.SDL_CONTROLLER_BINDTYPE_AXIS = en();
e.SDL_CONTROLLER_BINDTYPE_HAT = en();

e.SDL_CONTROLLER_AXIS_INVALID = en(-1);
e.SDL_CONTROLLER_AXIS_LEFTX = en();
e.SDL_CONTROLLER_AXIS_LEFTY = en();
e.SDL_CONTROLLER_AXIS_RIGHTX = en();
e.SDL_CONTROLLER_AXIS_RIGHTY = en();
e.SDL_CONTROLLER_AXIS_TRIGGERLEFT = en();
e.SDL_CONTROLLER_AXIS_TRIGGERRIGHT = en();
e.SDL_CONTROLLER_AXIS_MAX = en();

e.SDL_CONTROLLER_BUTTON_INVALID = en(-1);
e.SDL_CONTROLLER_BUTTON_A = en();
e.SDL_CONTROLLER_BUTTON_B = en();
e.SDL_CONTROLLER_BUTTON_X = en();
e.SDL_CONTROLLER_BUTTON_Y = en();
e.SDL_CONTROLLER_BUTTON_BACK = en();
e.SDL_CONTROLLER_BUTTON_GUIDE = en();
e.SDL_CONTROLLER_BUTTON_START = en();
e.SDL_CONTROLLER_BUTTON_LEFTSTICK = en();
e.SDL_CONTROLLER_BUTTON_RIGHTSTICK = en();
e.SDL_CONTROLLER_BUTTON_LEFTSHOULDER = en();
e.SDL_CONTROLLER_BUTTON_RIGHTSHOULDER = en();
e.SDL_CONTROLLER_BUTTON_DPAD_UP = en();
e.SDL_CONTROLLER_BUTTON_DPAD_DOWN = en();
e.SDL_CONTROLLER_BUTTON_DPAD_LEFT = en();
e.SDL_CONTROLLER_BUTTON_DPAD_RIGHT = en();
e.SDL_CONTROLLER_BUTTON_MISC1 = en();
e.SDL_CONTROLLER_BUTTON_PADDLE1 = en();
e.SDL_CONTROLLER_BUTTON_PADDLE2 = en();
e.SDL_CONTROLLER_BUTTON_PADDLE3 = en();
e.SDL_CONTROLLER_BUTTON_PADDLE4 = en();
e.SDL_CONTROLLER_BUTTON_TOUCHPAD = en();
e.SDL_CONTROLLER_BUTTON_MAX = en();

e.SDL_GameControllerButtonBind = Struct({
  bindType: 'int',
  value: Union({
    button: 'int',
    axis: 'int',
    hat: Struct({
      hat: 'int',
      hat_mask: 'int'
    })
  })
});

push_export({
  // TODO: for better day
});
